### ISSUE TITLE
UI Functionality - Refresh Page Button

### ISSUE THREAD

**Issue by markevan100** [josh-works/ruby_web_scraping#2]
Hi Josh-works, 

I was navigating your page an enjoying some blogs. Seems like it would be nice to have a button that would refresh the page for me with js rather than me having to know a hotkey or leave your site and head to the browser nav. Multiple ways to accomplish this with `location` or `history` or even setting it to refresh on its own at a set interval to keep me interested! 

Thanks!

**Comment by josh-works** [comment]
Typo in commit for closing #1, have not actually closed this yet.
